### ISSUE TITLE
error on awesome 3.5.6

### ISSUE THREAD

**Issue by ilovepumpkin** [setkeh/Awesome-3.5#4]
Hi, thanks for your effort. I am using Ubuntu 14.04 with Awesome 3.5.6. I got an error "module 'vicious' not found". From the error, it seems that it is looking for a file vicious.lua but it your files I only see a vicious directory. 
![image](https://cloud.githubusercontent.com/assets/11310645/8224881/3b438a8a-15c0-11e5-9dda-693bcfbb6069.png)

**Comment by setkeh** [comment]
It looks like when you have pulled the repo the link to the vicious repo did not work is there any files in the vicious directory and if not try pulling vicious your self if there is files c into that directory and update them by doing a git pull.

if you can please provide more info on how you ran into this error that would also be helpfull.

thanks,

**Comment by ilovepumpkin** [comment]
Yes, vicious is empty. I noticed that http://git.sysphere.org/vicious is broken - it says 'No repositories found'.

**Comment by setkeh** [comment]
try http://git.sysphere.org/vicious/ im not 100% sure why the trailing / matters but apparently it does ill add the new link to the pull and hopefully that resolves the issue :) its not really an issue with my repo just the linking to the vicious repo :D

**Comment by setkeh** [comment]
Ok i have fixed the Link in the Submodule and updated the README i had forgotten to add to the command the --recursive flag that tells git to download submodules after cloning master so you can either remove the config and re clone with the updated command (recommended so you get the new submodule) or you can try to update the submodule manually by doing the following .

    git submodule init
    git submodule update

but i cannot guarantee that will work since the link may still be broken in the commit you pulled but im not so sure it was completely to blame :D 

Hope this resolves the Issue for you.

**Comment by ilovepumpkin** [comment]
Thank you very much! :)
