### ISSUE TITLE
Vicious error

### ISSUE THREAD

**Issue by Kaitsh** [setkeh/Awesome-3.5#5]
![awesome](https://cloud.githubusercontent.com/assets/8351869/10583443/4bc85d26-768d-11e5-8942-09b91e435688.png)

I get an error if I start awesome. Unfortunately I am new to arch linux and awesome and don't really know what to do. I made a screenshot of the error.

**Comment by stevenan93** [comment]
Can you post your lua file?

**Comment by setkeh** [comment]
This appears to be a vicious issue you can likely resolve it by commenting out the gmail functions in you rc.lua if you could provide any modification you have made that would help.

**Comment by Kaitsh** [comment]
It was the gmail function. Thanks for your help!!

**Comment by ChenXiyu** [comment]
i got the same error , gmail dosen't work,
i wrote this to my gmail.lua:
```
-- Default is just Inbox
local feed = rss.inbox
local mail = {
    ["{count}"]   = "xycinus@gmail.com",
    ["{subject}"] = "N/A"
}
-- }}}
```
still don't work.
are i wrong?
please help me . thanks

**Comment by setkeh** [comment]
That section of code appears to be commented, if you are not looking to use the Gmail scripts then you need to comment out any reference to it in wi.lua and RC.lua instead of modifying the Gmail.lua directly.

Secondly this appears to be a vicious issue as I don't provide the Gmail.lua in my code please ensure your using the latest vicious release by cd into the vicious dir and git pull for the latest code.

Thirdly this issue is 7 months closed please next time create a new issue it's easier to track that way thanks.
