### ISSUE TITLE
background path

### ISSUE THREAD

**Issue by jonathf** [setkeh/Awesome-3.5#6]
Both ``themes/default/theme.lua`` and ``rc.lua`` is referring to the background ``themes/default/bg.png``. However, the file doesn't exist. I suppose it should be ``themes/default/background.png``.

**Comment by setkeh** [comment]
The idea is that you copy your own images to the wallpapers/ directory and use the wallpaper selector i built into the menu i have not provided a default bg.png because the menu can create one for you.


---

I have Added some default wallpapers thanks to Nasa and the Hubble Space Telescope and removed the broken symlink for bg.png.

Once you have Cloned the repo and are running this config for the first time you will se in the awesome menu a walpapers list you can select any of the wallpapers from there the awesome config will handle the rest, Awesome will restart every wallpaper change this is normal behaviour if you want your own images to show up in the list then copy them to,
	
	$HOME/.config/awesome/wallpapers/ 
	
and restart Awesome you can then select them from the drop down list.

**Comment by jonathf** [comment]
Thanks for the tip. I'll take a look at it.
